### PR TITLE
Added date support - restarted from master and added components from …

### LINKED ISSUE #17: Add date support for tasks and events

### PR DESCRIPTION
**Pull request by mchen14**
…Murray branch. However, made new temp branch because will eventually go back to Murray branch once errors are discovered and it isnt the day before the deadline. Fixes #17 .
Please pull from this branch (say git checkout MurrayTemp to switch branches) and see if you can run this before merging the pr please.

### CODE REVIEW

**Comment by mchen14** [comment]
Latest commit fixes #13

**Comment by mchen14** [comment]
#4 was also fixed with the first commit.

**Comment by JamesHuangUC** [comment]
gui shows up, but can't add/list

**Comment by mchen14** [comment]
adding requires a deadline at the moment. The error message should tell you the correct input for that.

**Pull request merged**
